cloud:
  aws:
    credentials:
      access-key: provide_details
      secret-key: provide_details
    s3:
      bucket-name: provide_details
file:
  upload:
    location: "C:/Learning/Spring/aws/test-files"
  download:
    location: "C:/Learning/Spring/aws/test-files-download"
    object: provide_details